### PR TITLE
Add network peers menu

### PR DESCRIPTION
**Pull request by leon332157**
Initially ported Edward's code to the more recent version.

Currently struggling to figure out how to expand the column width of the menu items as I would like to fit OS as well as ownership information, similar to `tailscale status` command. Would love some advice.

### CODE REVIEW

**Comment by kognise** [comment]
I pushed some updates and improvements to how I would like the UI to look.

However, there's a bug in the menu rendering code and it needs to be rewritten — it doesn't properly handle multi-line menu items and if many are on screen the top of the menu gets cut off. It needs some sort of progressive layout engine. I don't have the time right now but you could take a stab if you wanted!

**Comment by kognise** [comment]
jk it was easy i implemented it, push incoming

**Comment by leon332157** [comment]
For situations where the clipboard can not be accessed, over ssh for example, how do you plan to display the peer ip address?

**Comment by kognise** [comment]
After a little more thinking I definitely agree that IP would be more
helpful than host OS here. For now, I'll make an update to show the IP
instead.

Longer term we want an info window that shows multiple properties of the
host. I wanted to push out some sort of working peer menu before
implementing this but I will kick it off soon.

**Pull request merged**
